version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=proyecto.ch0yyu46sk3g.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_DATABASE=proyecto
      - DB_USERNAME=postgres
      - DB_PASSWORD=daniel2804
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
